---
# Include Encrypted Variables
- ansible.builtin.include_vars: vault.yml
  tags:
    - always

- ansible.builtin.import_tasks: prelim.yml
  tags:
    - always
    - vm_deps

- ansible.builtin.import_tasks: vm_lockdown.yml
  tags: stig

- name: Cleanup | Ensure VMs are started
  ansible.builtin.shell:
    cmd: |
      Connect-VIServer -Server {{ vcenter_hostname }} -User '{{ vcenter_username }}' -Password '{{ vcenter_password }}';
      $vms = Get-VM | where {$_.name -notMatch $exclusion_list} | Select-Object -ExpandProperty Name;
      ForEach($vm in $vms){
        $powered_state = Get-VM $vm | Select-Object PowerState;
        if($powered_state.PowerState -eq "PoweredOff"){
          Start-VM -VM $vm -Confirm:$False;
        }
      }
  args:
    executable: /usr/bin/pwsh
